### ISSUE TITLE
Adding tags - comma/full stop closes the entry

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#297] opened 2017-01-24 10:52 UTC
Comma and full stop in a tag acts in the same way as the enter key, and saves/closes the tag - is this intentional? We often use tags for the seminar title so they can be fairly long and include punctuation - if certain characters have system function would need to avoid them!
Thanks
Helen

**Comment by AndrewIsh** [comment] 2017-01-24 11:03
Hi Helen

I've not been able to replicate the full stop causing the tag to be saved, see attached screenshot:
![image](https://cloud.githubusercontent.com/assets/9194223/22244602/1e70a672-e224-11e6-9ece-31bd1e6281f0.png)
However, adding a tag upon a comma entry is by design, it ensures that users who are used to entering a list of tags separated by commas see expected behaviour. I'll leave this issue open in case other customers have similar requirements to enter commas. In the meantime, as a workaround, it is possible to paste in tags containing commas, these will not be separated into two tags. See screenshot below:
![image](https://cloud.githubusercontent.com/assets/9194223/22244762/c7200de4-e224-11e6-932d-8635a5ae3e7a.png)

I hope this helps
Andrew

**Comment by hloliver** [comment] 2017-01-24 15:11
Thanks Andrew, that makes sense about the comma and the workaround is fine for us. I haven't been able to replicate the issue with a full stop either so must have imagined it, or mis-typed (sorry!)
Helen

**Comment by AndrewIsh** [comment] 2017-01-24 15:17
OK, I'll close this issue. If you have further problems with this, feel free to re-open.

**Closed as completed by AndrewIsh** 2017-01-24 15:17 UTC
Labels: customer: tavi
