### ISSUE TITLE
Only able to add material to first 3 categories in a list

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#229] opened 2016-08-27 16:29 UTC
Hi

At the moment we can only add items to the first three categories of a list – the Add Item icons don’t change as you move down.

The three you can see below are for Note about the readings, Core texts – students are recommended to purchase their own copies, and Core Texts, so we can’t add anything to any of the other categories

can you take a look?
thanks
Helen

![image](https://cloud.githubusercontent.com/assets/12201255/18028619/be48228e-6c7b-11e6-93b4-f5e9aa450167.png)

**Comment by AndrewIsh** [comment] 2016-08-27 16:47
Hi Helen

The behaviour your seeing is by design. In order to avoid a long list of "Add material to X" buttons for customers with large numbers of categories, as you've observed, we only display buttons for the top 3 categories.

If you wish to add material to one of the other categories, clicking on the green "Add" button will allow you to add material to the top of the first category, at which point it can be moved into the correct place.

I hope this clarifies things. I'm going to close this issue, if you've got any further questions or are not seeing the behaviour I described, feel free to re-open.

Many thanks
Andrew

**Closed as completed** 2016-08-27 16:48 UTC
Labels: customer: tavi

**Comment by hloliver** [comment] 2016-08-28 07:21
Hi Andrew

Thanks for the explanation - this is quite different to the original direction that you were with going though! 

One of the big selling points at various demonstrations was that users would be able to add items to specific points in the list, saving a lot of scrolling around the list to move items to the correct place - and in the earlier versions of RL2 we were testing this was very popular with our staff.  Now we seem to be back to where we were with RL1 as it's fairly cumbersome dragging items to the right place, especially if you've got a long list with lots of new items to be inserted at different points.

It seems that a really useful new feature has been lost here.

best wishes
Helen

Helen Oliver

Systems Librarian
Tavistock & Portman NHS Foundation Trust
Tavistock Centre
120 Belsize Lane
London NW3 5BA

tel 020 8938 2318
email: holiver@tavi-port.ac.uk

**Comment by AndrewIsh** [comment] 2016-08-28 20:11
Hi Helen

Thanks for the feedback, very useful indeed. The reason for the change is that the majority of our customers don't have large numbers of categories, therefore three or four buttons is sufficient. However, I do agree that for customers with larger numbers of categories, this is a step backwards.

The suggestion you made in your first comment, whereby the "Add material to X" buttons change as you scroll down is an excellent one. I have, therefore, implemented this. As the user scrolls down the list, the categories that are visible on the screen at that moment are available as "Add material to X" buttons.

This addition will need testing, but I hope to be able to push it out to customers early next week.

I hope this is a helpful addition for you. I'll keep this issue closed. If you have further questions regarding this, feel free to re-open.

Many thanks
Andrew

**Comment by hloliver** [comment] 2016-08-31 07:21
Thanks Andrew, that would be really useful
best wishes
Helen

**Comment by AndrewIsh** [comment] 2016-08-31 07:41
Hi Helen

Just to let you know, this has now been pushed out to all customers

Many thanks
Andrew

**Comment by hloliver** [comment] 2016-08-31 09:22
Great, this works really well - thanks Andrew
Helen

**Comment by mrenvoize** [comment] 2016-09-05 13:54
Nice little enhancement there, well battled out.
