### ISSUE TITLE
Workflow for editing materials awkward

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/rebus-list-2#170] opened 2016-07-21 12:57 UTC
YSJ have queried the workflow for having to use Search for Materials in order to edit a manual entry:

"You might notice that there is an issue with material when you are in a list, e.g the title needs editing or some other element needs tidied, but you can't edit that item then and there, you need to note its details and then search for it again to edit it.  This is a bit frustrating when you've already had the details up on your screen.  It would be good if you could edit it wherever you see it."

Any thoughts to re-work in future?

**Comment by paulwilliamsBCU** [comment] 2016-07-21 16:10
We'd like to support this request at BCU. I've had quite a few comments from our testers saying that this is difficult to manage. They effectively want an edit button next to the item in question.

**Comment by mrenvoize** [comment] 2016-07-22 08:42
I totally agree it's awkward at the moment, and it's one on our to do list to improve.

The issue is, the material editing is outside the moderation workflow so we need to come up with a sensible way around this.

**Comment by AndrewIsh** [comment] 2017-07-26 13:52
In place editing of materials within a list is now available. Closing.

**Closed as completed by AndrewIsh** 2017-07-26 13:52 UTC
Labels: type: enhancement, customer: bcu, customer: sunderland, customer: ysj, customer: staffs
