### ISSUE TITLE
'Add to list as' not working #324 - still not working

### ISSUE THREAD

**Issue by hloliver** [PTFS-Europe/rebus-list-2#325] opened 2017-05-05 18:24 UTC
Hi Andrew - sorry reopening #324 as I've just tried adding several items from a search using the Koha connector, they loaded into the list but when I published the list the items disappeared.

List no.#/4140 (at around 19.21 in case you need to check logs)

Have opened this as a new call - couldn't see a way of reopening the existing one (last time I commented on a closed call it didn't get through)

best wishes
Helen

**Comment by AndrewIsh** [comment] 2017-05-08 11:22
Hi Helen

Thanks for this. Sorry to hear you're still having problems. We've identified the cause and have now fixed it. The fix will be pushed out to your server tonight.

Apologies for the inconvenience.

Regards
Andrew

**Comment by hloliver** [comment] 2017-05-09 08:51
Thanks Andrew - all working fine now
bw
Helen

**Comment by AndrewIsh** [comment] 2017-05-09 13:20
Thanks for letting me know.

**Closed as completed by AndrewIsh** 2017-05-09 13:20 UTC
