### ISSUE TITLE
UHI - Hierarchy re-ordering and adding units

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#201] opened 2016-08-12 12:41 UTC
Hi

We aren't able to move lists to a new location in the hierarchy structure, we continually get the red error message when we drag and drop.  

![hierarchy move](https://cloud.githubusercontent.com/assets/17139950/17622470/7b493774-6092-11e6-8c0c-c270aee707e6.png)

Also, the "Add new unit" button at the top doesn't work either. When hovering over it, we get the circle with red line through it, it can't be clicked. 

Please can you have a look at both issues? 

Thanks

Richard

**Comment by AndrewIsh** [comment] 2016-08-15 09:29
Hi Richard

Thanks for the report. It would appear that your hierarchy got stuck in a locked state (which is temporarily applied when a clone operation is ongoing). I've now cleared the lock. Try again, feel free to re-open this issue if it happens again.

Many thanks
Andrew

**Comment by richughes** [comment] 2016-08-17 09:41
Hi @AndrewIsh 

Can we re-open this? We are still unable to move lists in hierarchy, it worked briefly the other day but we are now getting the same error message as before. 

Renaming lists is also a problem. When editing the name in the hierarchy, saving it produces a red error. When a change seemingly does save successfully with the green box, the public view of the list retains the old name. Eventually the new name reverts to the old one in the hierarchy, undoing any changes. 

Thanks

Richard

**Comment by AndrewIsh** [comment] 2016-08-18 09:54
Hi Richard

I've now re-opened this and will investigate.

Many thanks
Andrew

**Comment by richughes** [comment] 2016-09-09 09:43
Hi @AndrewIsh 

Have you had a chance to have another look at this? When we create new lists, we still can't drag them into the correct area of the hierarchy. Error message everytime. 

Thanks

Richard

**Comment by mrenvoize** [comment] 2016-09-09 14:08
@AndrewIsh, you don't appear to be displaying the error messages in those popups as they come back from the API at the moment :(.. Is that not a regression?

**Comment by mrenvoize** [comment] 2016-09-09 14:12
@richughes, this to me looks like there was an issue with the validity dates of the lists in question.. which should have been clearer had the error message been properly reported.

I just tried to move a list within your 'UNMAPPED Lists' set and at first it was not happy as the validity dates were outside of the parents dates (an error in my early migration I think).

In short, as we practice inheritance, it makes no sense for a child 'list' to have a validity period that falls outside of the parent 'unit', and thus the action was blocked.

I believe this should be fixed now, could you try and confirm for me?

**Comment by richughes** [comment] 2016-09-09 15:03
@mrenvoize  I'm now able to move the list we were having difficulty with. Thanks

I had never really thought about the validity dates affecting movement of lists, will bear it in my mind if we have problems in future.

**Comment by mrenvoize** [comment] 2016-09-09 15:07
@richughes I've taken the liberty of 'fixing' all the validity_dates from the original load.. I think they were a bit all over the place due to how we've been refining the system over time.  What i've done is set the top level ones to a 'sensible' 1 year period for this academic year, and then removed all explicit dates beneath those top units so that they inherit.  This seemed sensible as from an inspection of the database it didn't look like you were using the explicit functionality at so far and rather using defaults as per the prior workings of the system.

The knock on effect should mean rollover should work more predictably when the time comes down the line, and you may of course add explicit dates more thoroughly at your leisure.

Many thanks, 

Martin

**Comment by mrenvoize** [comment] 2016-09-09 15:07
Excellent, let me know if you have any future issues.

Martin

**Closed as completed by mrenvoize** 2016-09-09 15:07 UTC
Labels: customer: uhi
