### ISSUE TITLE
Enhancement request for Set browse in Alpha order

### ISSUE THREAD

**Issue by janetc** [PTFS-Europe/rebus-list-2#214] opened 2016-08-18 14:25 UTC
Bucks and YSJ - whilst you can move materials around to display in the hierarchy, to be able to rearrange lists within a unit in Alpha order by clicking a button seems to be considered a nice feature.

**Comment by mrenvoize** [comment] 2016-08-22 19:34
Duplicate of #186

**Closed as completed** 2016-08-22 19:34 UTC
Labels: type: enhancement, customer: ysj, customer: bucks, customer: staffs
