### ISSUE TITLE
System freezing during search (Chrome browser)

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#57] opened 2016-02-09 10:33 UTC
When searching for resources using the "add new item" function within a list in the Chrome browser, the search time is extremely slow, taking a few minutes. The following message then appears:

![unresponsive script](https://cloud.githubusercontent.com/assets/17139950/12913712/44ee6dfe-cf18-11e5-81ce-ab08f189bf67.PNG)

**Comment by AndrewIsh** [comment] 2016-02-09 10:40
Hi Richard

Are you seeing this problem after adding several items, or immediately when adding the first item to a list?

Could you please refresh the page and try again, and let me know whether it improves?

Many thanks
Andrew

**Comment by richughes** [comment] 2016-02-11 15:25
Hi Andrew

Kasia tells me that performance was much better yesterday (feb 10th), but that it has been very patchy today. She's finding it difficult to make many edits as she is continuously being asked to login when trying to edit lists and also when just accessing the homepage. I've tried the homepage a few times and get prompted with the login screen before doing anything as well. 

Is there work going on today that has reduced performance?

Thanks

Richard

**Comment by AndrewIsh** [comment] 2016-02-12 08:37
Hi Richard

There wasn't any work happening yesterday that might have reduced performance, so I'm puzzled why she found it poor. Next time she experiences this problem, could you ask her to log out, refresh the page, then log in again and see if performance improves, if you could let me know the results that would be great.

Repeatedly being asked to log in is an interesting one, I think Kasia and you were experiencing different aspects of the same issue. When using the site after a period of inactivity (the default is one hour), if you didn't explicitly log out, your session will have expired and you will be prompted to log in regardless of what page you are viewing, I think this is what you are seeing.

I'm not sure what's happening with Kasia, it sounds like she has an expired session, but assuming she logged in, that should have gone away. When it happens, can you ask her to log out, then log back in again and see if that solves it, and let me know. That should help me to narrow down what's happening.

Also, as an aside, when you see odd behaviour like this, can you make a note of the time and submit it with the Github issue, it will enable me to look in the log files and see if there are any clues as to what might be happening.

Many thanks
Andrew

**Comment by richughes** [comment] 2016-02-12 13:29
Hi Andrew

I've attached a word document that Kasia sent this morning with some details of the issues she's been having today, primarily in Chrome. She has included the time that the issues occured. I've been using Firefox today and it's seemed fine, but I'm not adding as many resources to lists as she is.

Thanks

Richard
[Rebus error messages Fri12thFeb.docx](https://github.com/PTFS-Europe/rebus-list-2/files/128035/Rebus.error.messages.Fri12thFeb.docx)

**Comment by AndrewIsh** [comment] 2016-02-12 14:20
Hi Richard

Many thanks for the update. Kasia's notes confirm what I've been suspecting, I think I know what the reason for the slowdown is. I'll add this as a top priority to fix, in the meantime, can you tell Kasia that, in the meantime, refreshing the page once it starts getting bad should resolve it temporarily.

Thanks
Andrew

**Comment by AndrewIsh** [comment] 2016-02-15 16:47
Hi Richard

I have today created what should be a fix for this issue (and, quite possibly, issue #59 also). Once it has undergone additional testing, we'll push it to your server. I'll let you know once this has been done.

Thanks
Andrew

**Comment by richughes** [comment] 2016-02-16 16:11
Hi Andrew

Kasia sent me this picture today, I'm adding it here in case it's related to the same fix you're working on. Let me know if it needs a separate issue logged.

![chrome error patch](https://cloud.githubusercontent.com/assets/17139950/13082258/df38d99e-d4c7-11e5-9826-613f10361574.PNG)

Many thanks

RIchard

**Comment by AndrewIsh** [comment] 2016-02-16 18:00
Hi Richard

That's definitely a different issue. Can you ask Kasia what she was doing when this message appeared? Once I know that, I'll create a new issue.

Many thanks
Andrew

**Comment by richughes** [comment] 2016-03-16 13:55
Hi Andrew

The unresponsive screen has started appearing again in Chrome, my colleague Kathleen has been having difficulties with it earlier today. The screenshot was taken at 12:11.

![chrome list freeze](https://cloud.githubusercontent.com/assets/17139950/13814446/338f2490-eb7e-11e5-855b-da61308572a7.png)

The list being used at the time was: https://uhi.rebuslist.com/#/list/1581 

Many thanks

Richard

**Comment by AndrewIsh** [comment] 2016-03-16 14:30
Hi Richard

Thanks for the update. We've been having some problems with the Preview server today, particularly around the time Kathleen was having problems. Can I ask her to log out, refresh her screen, then log back in again and see if she still has problems?

Many thanks
Andrew

**Comment by AndrewIsh** [comment] 2016-07-05 09:56
I'll close this issue as I'm assuming the problem is no longer being seen. Feel free to reopen if that is not the case.

**Closed as completed by AndrewIsh** 2016-07-05 09:56 UTC
Labels: customer: uhi
