### ISSUE TITLE
UniofSunderland - Editing entries on lists

### ISSUE THREAD

**Issue by UniofSunderland** [PTFS-Europe/rebus-list-2#245] opened 2016-09-21 11:27 UTC
Recent testing has shown that we are unable to edit at item entry level on lists - we can add to lists and edit exisiting lists but not any existing entries.

**Comment by AndrewIsh** [comment] 2016-09-21 11:43
Hi

Thanks for this. Could you please give a bit more detail about how you are trying to edit entries?

Many thanks
Andrew

**Comment by mrenvoize** [comment] 2016-11-07 10:31
Closing as duplicate of #170 

We are actively working on improving this area at the moment.

**Closed as completed** 2016-11-07 10:32 UTC
Labels: customer: sunderland
