### ISSUE TITLE
Unable to edit or publish list

### ISSUE THREAD

**Issue by SharonCocker** [PTFS-Europe/rebus-list-2#52] opened 2016-01-25 12:02 UTC
I recently created a sub-list named "HQ Test List" within our "LRS" test list - I was origninally able to add items, but at the time unable to publish the list (unsure why).  Today I am now unable to edit this list at all and keep receiving a red error message.    

My permissions are set up as "admin".   

Thanks,
Heather

**Comment by AndrewIsh** [comment] 2016-01-25 12:35
Hi Sharon

Thanks for this, any details on what the "red error message" says?

Many thanks
Andrew

**Comment by AndrewIsh** [comment] 2016-01-25 12:37
Also, what user are you logged in as?

**Comment by SharonCocker** [comment] 2016-01-25 13:36
I'm logged in as lb1hq (my full name is Heather Quinn).   I've just tried to replicate the problem and taken a screenshot of the error at the same time - see attached.  

Thanks,
Heather
![rebus 2 0 screenshot error edit list](https://cloud.githubusercontent.com/assets/12249067/12552268/9ed21016-c368-11e5-8f25-03c7453bee03.png)

**Comment by AndrewIsh** [comment] 2016-01-25 14:13
Hi Heather (sorry for calling you Sharon earlier!)

Thanks for the screenshot, very useful. I just tried to replicate the error, but notice that Joanna Bek has an open editing session on that list. Could you let me know when she is finished and I'll investigate.

Many thanks
Andrew

**Comment by SharonCocker** [comment] 2016-01-25 14:22
Hi Andrew,

We were just testing it together as Joanna is also having problems. She 
can log in, but can't do anything else - ie cannot edit in any way.  
She's tried altering her enablements, but to no avail.  We are both now 
logged out.

Thanks again,
Heather

Heather Quinn
Learning Resources Section
Digital Services and Systems Team
Western Bank Library
University of Sheffield
Western Bank
SHEFFIELD S10 2TN

Tel: 0114 22 27249
Email: h.quinn@sheffield.ac.uk

**Comment by AndrewIsh** [comment] 2016-01-25 14:37
Thanks for that Heather. Can I just check, are you getting this error when you click the "Edit this list" button?

**Comment by SharonCocker** [comment] 2016-01-25 15:06
Yes, the error appears when I click on "Edit this list".   The other day 
I was able to edit, but not publish and then strangely today I can't 
even edit.    In case it has any bearing on the issue, when I could edit 
I found that tagging wasn't working for me - though I haven't got round 
to reporting it yet.   When I added a tag to an item, the item 
duplicated itself and appeared directly below.   If this is a separate 
issue, I'll report this once I'm back up and running.

thanks,
Heather

Heather Quinn
Learning Resources Section
Digital Services and Systems Team
Western Bank Library
University of Sheffield
Western Bank
SHEFFIELD S10 2TN

Tel: 0114 22 27249
Email: h.quinn@sheffield.ac.uk

**Comment by AndrewIsh** [comment] 2016-01-25 15:10
OK, that's very interesting, I noticed there were duplicate tags on one of the items, which is extremely odd. I've now removed this. I'm not sure if this is what was causing your problems editing the list, can you try now and let me know if you're able to?

Many thanks.

**Comment by SharonCocker** [comment] 2016-01-25 15:26
Still problems unfortunately.  This time when I click on edit, another login box appears.  I've tried just closing it and trying again - and also tried logging in again - but neither seems to work.   I then receive an error message again.  Screenshots attached of both the repeated login box and the second error message.   

![rebus 2 0 screenshot error further login](https://cloud.githubusercontent.com/assets/12249067/12555152/a7d9291a-c377-11e5-9558-8d20f06879aa.png)
![rebus 2 0 screenshot error edit list2](https://cloud.githubusercontent.com/assets/12249067/12555157/ab375424-c377-11e5-804a-c262be181f01.png)

**Comment by AndrewIsh** [comment] 2016-01-25 16:04
OK, I think I know what the problem is, I see you're on Chrome, so could you please do the following for me:
- Ensure you're logged out of rebus:list 2
- Click on the 3 bars in the top right hand corner, just below the "X"
- Choose "Settings"
- Click "Show advanced settings" at the bottom of the screen
- Click the "Content settings" button
- Click the "All cookies and site data" button
- In the top right, in the "Search cookies" box, type "preview2" (without the quotes)
- Hover over the "preview2.rebuslist.com" result, and click the "X" on the right hand side of the row
- Click the "Finished" button
- Click the next "Finished" button
- Close the "Settings" tab

Once this is done, go back to rebus:list 2, log in, then try and edit the list, you should be able to get in, let me know if not.

It seems as though you've found a bug, which I'll log now. You shouldn't experience the problem again, but if you do, let me know. I'd be particularly interested if you're able to replicate the problem with tags being duplicated.

Many thanks
Andrew

**Comment by SharonCocker** [comment] 2016-01-26 09:16
Morning Andrew,
I tried the fix and all appeared to work okay at first.   I clicked on edit a list and the orange header appeared.   For the three repeated entries ("The Great Transformation") I had had problems with the other day, I tried to delete two of them and then clicked to publish the list.   All appeared fine.  I then tried to edit the list again - intending to add some more items - however, I couldn't access edit properly (no orange header appeared), strangely the two deleted entries re-appeared and an error message was displayed.   I tried the Chrome cookies fix again and repeated what I had done - edit worked and I deleted (again) two of the three repeated entries and then published the list.  However, when I then tried again to go back in to add more items, as soon as I clicked on the edit the list button, the exact same problem happened, ie the deleted entries re-appeared yet again and I had the same error message.   Please see screenshots attached.   

On a slightly different note, as the 'publish' / 'draft' function is quite different to v.1, I'm a little unsure whether I am trying to use them correctly.   Perhaps it's because things are working quite right yet, but I find it difficult to tell easily when a list is published and when it is still in draft.   Also, at what point should I click on 'draft' - will the items not save if I don't and also don't publish?  Apologies, I'm sure I'll be more au fait once I get into it! 

Cheers,
Heather

![rebus 2 0 screenshot after deleted entries](https://cloud.githubusercontent.com/assets/12249067/12576332/d3ca257c-c40a-11e5-973a-1359fc939849.png)
![rebus 2 0 screenshot deleted entries reappearing with error](https://cloud.githubusercontent.com/assets/12249067/12576337/d72f726c-c40a-11e5-87a5-4f072d946bfb.png)

**Comment by mrenvoize** [comment] 2016-01-26 10:20
Hi Heather, 

Andrews had to take a last minute day off today to look after his poorly son.

I believe I have just fixed the login box issue this morning and will attempt to follow-up on Andrews leads from yesterday.

Thankyou for reporting these issue, they're really helpful in tracking down these illusive bugs and getting the system ready fro prime time.

Martin

**Comment by SharonCocker** [comment] 2016-01-26 11:22
Hi Martin,

Many thanks for getting back to me.  I have it in my diary to do a bit 
more testing tomorrow, so will be in touch with any findings. Please 
pass on my best wishes to Andrew and I hope his son is better soon.

Best wishes,
Heather

Heather Quinn
Learning Resources Section
Digital Services and Systems Team
Western Bank Library
University of Sheffield
Western Bank
SHEFFIELD S10 2TN

Tel: 0114 22 27249
Email: h.quinn@sheffield.ac.uk

**Comment by AndrewIsh** [comment] 2016-01-27 10:15
Hi Heather

Thanks for your latest update. Some interesting information there. I'm going to spend some time today trying to get to the bottom of it. Many thanks for your continued help with this! :-)

Thanks
Andrew

**Comment by SharonCocker** [comment] 2016-01-27 11:11
Hi Andrew,

Just done a quick bit of testing in Chrome and also Firefox - edited my list, added items, tags, notes and also moved items around to different sections of the list.   All appeared okay and I didn't encounter any of the previous problems.   

Thanks,
Heather

**Comment by AndrewIsh** [comment] 2016-01-27 11:15
Hi Heather

That's promising. I notice a new category appeared too, did you add that? 

Thanks
Andrew

**Comment by SharonCocker** [comment] 2016-01-27 11:20
Hi Andrew,

I didn't intentionally create a new category, just moved items between 
the sections.

Essential
Core
Recommended
Background

Does that help?
Heather

Heather Quinn
Learning Resources Section
Digital Services and Systems Team
Western Bank Library
University of Sheffield
Western Bank
SHEFFIELD S10 2TN

Tel: 0114 22 27249
Email: h.quinn@sheffield.ac.uk

**Comment by AndrewIsh** [comment] 2016-01-27 14:12
Hi Heather

It does help, thanks. So, in the list edit view, you dragged some items from one category to another and it created a new category?

Thanks
Andrew

**Comment by SharonCocker** [comment] 2016-01-27 14:30
Hi Andrew,

I've just had a look at my colleague's test list (Joanna Bek) "JB test 
list" as didn't take much notice of what each category was name before I 
moved items around.   Joanna's has the same categories as mine, ie

Essential
Core
Recommended
Background
Category
- so I don't think it did create a new category.   Can you see something 
  different to the ones I can see?

Heather

Heather Quinn
Learning Resources Section
Digital Services and Systems Team
Western Bank Library
University of Sheffield
Western Bank
SHEFFIELD S10 2TN

Tel: 0114 22 27249
Email: h.quinn@sheffield.ac.uk

**Comment by AndrewIsh** [comment] 2016-01-27 15:24
Hi Heather

Yes, I'm seeing the same categories, I'm just wondering where the one called "Category" came from, I'm guessing someone somewhere created it while testing, nothing to worry about.

OK, so have you seen stable behaviour today, or any repeats of the problems of a few days ago?

Thanks
Andrew

**Comment by SharonCocker** [comment] 2016-01-27 15:27
I only did a little testing today, but all appeared stable and none of 
the oddities, repeated items, etc appeared.    (I tried both Chrome and 
Firefox btw.)

Heather

Heather Quinn
Learning Resources Section
Digital Services and Systems Team
Western Bank Library
University of Sheffield
Western Bank
SHEFFIELD S10 2TN

Tel: 0114 22 27249
Email: h.quinn@sheffield.ac.uk

**Comment by AndrewIsh** [comment] 2016-01-27 15:33
OK, that's good news. I'm going to leave this issue open, but haven't been able to replicate the problems you've seen, but have a suspicion as to the cause. I'm going to make some changes which will hopefully prevent it happening again.

Thanks
Andrew

**Comment by AndrewIsh** [comment] 2016-07-05 09:53
A fix was pushed out for this some time ago. If you are still seeing this problem, feel free to re-open this issue. I'll close it for now though.

**Closed as completed by AndrewIsh** 2016-07-05 09:53 UTC
