### ISSUE TITLE
Search for material - edit item freezing

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#105] opened 2016-03-17 11:36 UTC
Hi

When I try to edit an item in the Search for Material area the system freezes in Chrome. The item was (SCRAN online) added about 10 minutes beforehand. The record came from COPAC and I was trying to add a URL. 

![search for material](https://cloud.githubusercontent.com/assets/17139950/13844839/208485fa-ec34-11e5-9c00-13ebcbbaa98b.png)

After waiting for the page to become responsive again, I still cannot edit the item and the Finish/cancel buttons do not work. Closing the browser tab is the only way out. 

Many thanks

Richard

**Comment by AndrewIsh** [comment] 2016-03-17 13:09
Hi Richard

Many thanks for that. Can I ask, roughly how long had you been using rebus:list today before you saw this? Also, when you started today was it in a new browser window or was it in a window that you'd previously opened?

Many thanks
Andrew

**Comment by richughes** [comment] 2016-03-17 13:23
Hi Andrew

I’d only just opened Chrome just before starting work on Rebus, I found that in general it’s the best browser for editing. I’d been using it for about 20 minutes to add list items, then switched to “Search for material” so I could manually edit a URL.

I think I still appeared to be logged in from yesterday, but if I remember rightly I was prompted to login again once I clicked edit mode.

Many thanks

Richard

**Comment by AndrewIsh** [comment] 2016-06-17 15:35
Hi Richard

This problem was caused by the same bug as this issue: https://github.com/PTFS-Europe/rebus-list-2/issues/119 and has therefore been fixed.

I'll close this issue, feel free to re-open if the problem persists.

Many thanks
Andrew

**Closed as completed by AndrewIsh** 2016-06-17 15:35 UTC
Labels: customer: uhi
