### ISSUE TITLE
Problem with Notes Field in Decription Tab

### ISSUE THREAD

**Issue by paulwilliamsBCU** [PTFS-Europe/rebus-list-2#192] opened 2016-08-08 13:56 UTC
Hi

When adding an item manually, the Notes metadata field in the Description tab seems to be coded incorrectly. It looks like it is expecting an 'array' (please see attached).

[Notes.docx](https://github.com/PTFS-Europe/rebus-list-2/files/406925/Notes.docx)

**Comment by mrenvoize** [comment] 2016-08-08 17:47
Thanks for the report @paulwilliamsBCU,  that is certainly a bug. I'll get @andrewish on the case as soon as he's back from leave

**Comment by mrenvoize** [comment] 2016-08-18 06:58
Added to the queue

**Comment by mrenvoize** [comment] 2016-08-18 07:06
Duplicate of #183

**Closed as completed by mrenvoize** 2016-08-18 07:06 UTC
Labels: type: bug, customer: bcu

**Comment by AndrewIsh** [comment] 2016-08-22 08:08
Hi @paulwilliamsBCU 

Just to let you know, I've just pushed out a fix for this. It should be on your server later this morning.

Many thanks
Andrew
