### ISSUE TITLE
Publication date in manual entries

### ISSUE THREAD

**Issue by richughes** [PTFS-Europe/rebus-list-2#62] opened 2016-02-15 14:31 UTC
Hi

When adding a publication date in manual entry the date has to be chosen using a calendar. When it's a publication more than a few years old, it takes a large number of mouseclicks to get to the correct year, eg 1985 = 360 clicks. 

![manual entry calendar](https://cloud.githubusercontent.com/assets/17139950/13051292/46f00662-d3f0-11e5-9735-77faea5e86a8.png)

Can you change it so that dates can also be typed? If not, can another arrow be added to the calendar that skips a full year at a time, rather than just month by month. 

Many thanks

Richard

**Comment by AndrewIsh** [comment] 2016-02-15 14:59
Hi Richard

Thanks for this. This issue is something that has been brought to our attention by another user. We're currently working on an improved date picker that will enable easier entry of dates, including those a long time in the past.

I'll close this issue as it's a duplicate of #48 

Regards
Andrew

**Closed as completed by AndrewIsh** 2016-02-15 14:59 UTC
Labels: customer: uhi
